version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - ENVIRONMENT=production
      - WORKERS=4
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
